### ISSUE TITLE
IBatchRendererStdOptions type in BatchRendererPluginFactory requires geometryFactory

### ISSUE THREAD

**Issue by m8ypie** [pixijs/pixi-batch-renderer#5]
In the BatchRendererPluginFactory.ts the interface, IBatchRendererStdOptions, is requiring that geometryFactory be passed. 

However it doesnt seem to be referenced anywhere else, specifically IBatchRendererOptions within BatchRenderer.ts appears to not have any reference to this required field. 

Am I missing something, if so can you point me to some documentation on how to properly pass a instantiated geometryFactory to BatchRendererPluginFactory?

**Comment by SukantPal** [comment]
@m8ypie You must pass a **geometry class** and not a instantiated geometry object. See this: https://github.com/pixijs/pixi-batch-renderer/blob/87ceafedf92809da765ca83791fbe9a65d3187b1/src/BatchRendererPluginFactory.ts#L25

If you create a geometry-factory class, then it's constructor takes just one parameter - the batch-renderer itself:

https://github.com/pixijs/pixi-batch-renderer/blob/87ceafedf92809da765ca83791fbe9a65d3187b1/src/BatchRenderer.ts#L352

**Comment by SukantPal** [comment]
Ah, I see. `geometryFactory` is not supposed to exist. It is a leftover from previous version of pixi-batch-renderer. Please ignore it.

**Comment by SukantPal** [comment]
You don't have to pass a geometry-factory; this is the default https://github.com/pixijs/pixi-batch-renderer/blob/master/src/BatchGeometryFactory.ts.

I'll fix this issue tomorrow & remove `geometryFactory` from the options interface.

**Comment by m8ypie** [comment]
Cheers @SukantPal

**Comment by m8ypie** [comment]
Also, I think vertexCountProperty and stateFunction should be flagged as optional as well considering they are given default values if not defined in BatchRenderer.ts

**Comment by SukantPal** [comment]
@m8ypie I fixed this issue. Please update to pixi-batch-renderer@2.1.2 (https://www.npmjs.com/package/pixi-batch-renderer). Feel free to reopen this if it didn't solve the issue.

* `vertexCountProperty` & `indexProperty` are optional

* `geometryFactory` was removed
